### PR TITLE
fix highlighting multi-digit numbers

### PR DESCRIPTION
**Pull request by AlexPoulsen**

### CODE REVIEW

**Comment by AlexPoulsen** [comment]
it removes regex `\b` tags, which fixes highlighting multi-digit numbers for whatever reason

**Comment by bendmorris** [comment]
Can you give an example that this fixes the highlighting for? Because I'm seeing the same thing with both. It doesn't seem right to remove the `\b` - it would match numbers inside other tokens.

**Comment by AlexPoulsen** [comment]
**With `\b`:**
Screen Shot 2019-03-30 at 12 57 26 PM
Screen Shot 2019-03-30 at 12 57 07 PM
**Without `\b`:**
Screen Shot 2019-03-30 at 12 58 07 PM
Screen Shot 2019-03-30 at 12 55 50 PM

**Comment by AlexPoulsen** [comment]
it's not perfect, the hex literal isn't colored right, but it's better

**Comment by bendmorris** [comment]
I made a recent fix to this, and I suspect you're looking at a commit prior to that. Here's what I see (color scheme changed to emphasize the numbers):

image

The `\b` is still needed though, and that wouldn't affect matching multiple digit numbers, it prevents matching inside of other words. Not having them breaks hex parsing for example:

image

There are two improvements we could make, and you're welcome to make them here if you'd like to:

- Instead of `\b` at the beginning, use `(\b|-)` to capture leading negative sign
- The hex literal should accept `A-F` in addition to `a-f`

**Comment by AlexPoulsen** [comment]
so it turns out my code to install the package had a bug and so i probably had an old version in there

**Pull request closed without merging**
