### PR TITLE
Add map to standard library

### PR DESCRIPTION
**Pull request by Gamerfiend**
Map is a hashmap implementation to the standard library under map.

### CODE REVIEW

**Comment by bendmorris** [comment]
You mentioned you were also creating tests - can you add those to the PR?

I'd like to have a test in tests/compile-src/std/map.kit - see the other tests in that directory for examples. If you create a second file called `tests/compile-src/std/map.stdout`, it'll check that the output of the test matches that file.

**Comment by Gamerfiend** [comment]
Okay I’ll work on that :)

**Comment by Gamerfiend** [comment]
@bendmorris I added tests, they get a single error that yaml also has, from an unexpected value? But other than that they pass! Let me know if I did it wrong, or some changes are needed.

**Comment by Gamerfiend** [comment]
@bendmorris I think I got all the formatting correct, let me know if there are any more changes needed, I'll update the rules when it gets fixed and add some new rules later for auto unwrapping

**Pull request merged**
